// This file is auto-generated by Supabase.
// Run: npm run db:types  (or: supabase gen types typescript --project-id YOUR_PROJECT_ID)
// Do not edit manually.
//
// Until you run the generator, this stub keeps TypeScript happy.

export type Database = {
  public: {
    Tables: {
      users: { Row: any; Insert: any; Update: any }
      learning_paths: { Row: any; Insert: any; Update: any }
      lessons: { Row: any; Insert: any; Update: any }
      quiz_questions: { Row: any; Insert: any; Update: any }
      user_progress: { Row: any; Insert: any; Update: any }
      skill_scores: { Row: any; Insert: any; Update: any }
      achievements: { Row: any; Insert: any; Update: any }
      user_achievements: { Row: any; Insert: any; Update: any }
      mentor_conversations: { Row: any; Insert: any; Update: any }
      waitlist: { Row: any; Insert: any; Update: any }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
