-- ─────────────────────────────────────────────────────────────────────────
-- Seed: Foundations path lessons + quiz questions
-- Run after 001_initial_schema.sql
-- ─────────────────────────────────────────────────────────────────────────

-- Grab the path IDs we need
do $$
declare
  foundations_id uuid;
  databases_id   uuid;

  l1 uuid; l2 uuid; l3 uuid; l4 uuid; l5 uuid;
  l6 uuid; l7 uuid; l8 uuid;
  d1 uuid; d2 uuid; d3 uuid;
begin

  select id into foundations_id from public.learning_paths where slug = 'foundations';
  select id into databases_id   from public.learning_paths where slug = 'databases';

  -- ── Foundations lessons ────────────────────────────────────────────────

  insert into public.lessons (id, path_id, slug, title, content_mdx, order_index, type, xp_reward, is_free)
  values (uuid_generate_v4(), foundations_id, 'how-the-web-works', 'How the Web Works', E'## What actually happens when you type a URL?\n\nMost developers can build a login form. Far fewer can explain what happens between the moment you press Enter and the moment the page appears.\n\nUnderstanding this end-to-end flow is the foundation of system design thinking.\n\n## The journey of a request\n\nWhen you type `https://twitter.com` into your browser:\n\n**1. DNS resolution**\n\nYour browser first needs to find the IP address of `twitter.com`. It checks:\n- Browser cache\n- OS cache\n- Your router\n- Your ISP''s DNS resolver\n- Root DNS servers\n\nThis is called a **DNS lookup**. It usually takes < 1ms from cache, or up to 100ms for a fresh lookup.\n\n**2. TCP connection**\n\nWith the IP address, your browser opens a TCP connection to the server on port 443 (HTTPS). This requires a **3-way handshake** — SYN, SYN-ACK, ACK — which takes one round trip.\n\n**3. TLS handshake**\n\nFor HTTPS, after TCP comes TLS negotiation. The server proves its identity via a certificate, and both sides agree on encryption keys. Adds another 1-2 round trips.\n\n**4. HTTP request**\n\nFinally, your browser sends an HTTP GET request:\n\n```\nGET / HTTP/1.1\nHost: twitter.com\nAccept: text/html\n```\n\n**5. Server processes the request**\n\nThe request hits a load balancer, which routes it to one of many web servers. The server generates a response — usually HTML, often pulled from a cache or database.\n\n**6. Response and rendering**\n\nThe server sends back an HTTP response. Your browser parses the HTML, discovers CSS and JS it needs, fetches those, and renders the page.\n\n## Why this matters for system design\n\nEvery one of these steps is a potential bottleneck:\n\n- Slow DNS? Add DNS caching.\n- Slow TCP handshake to distant servers? Add a CDN closer to users.\n- Server overloaded? Add load balancing.\n- Database slow? Add caching.\n\n> **Key insight**: System design is mostly about identifying which step is the bottleneck and fixing it without breaking the others.', 1, 'lesson', 10, true)
  returning id into l1;

  insert into public.lessons (id, path_id, slug, title, content_mdx, order_index, type, xp_reward, is_free)
  values (uuid_generate_v4(), foundations_id, 'client-server-model', 'The Client-Server Model', E'## Every app is a conversation\n\nAt the heart of every web application is a simple conversation between two parties:\n\n- **Client**: the entity making requests (browser, mobile app, another server)\n- **Server**: the entity responding to requests\n\n## HTTP: the language of the web\n\nHTTP (HyperText Transfer Protocol) is how clients and servers talk. Every interaction follows a request/response cycle.\n\n### Anatomy of an HTTP request\n\n```\nMETHOD /path HTTP/1.1\nHeader-Name: value\n\nRequest body (for POST/PUT)\n```\n\nThe **method** describes the intent:\n| Method | Intent |\n|--------|--------|\n| GET    | Retrieve data |\n| POST   | Create something |\n| PUT    | Replace something |\n| PATCH  | Update part of something |\n| DELETE | Remove something |\n\n### HTTP status codes\n\n- **2xx** — success (200 OK, 201 Created)\n- **3xx** — redirect (301 Moved, 302 Found)\n- **4xx** — client error (400 Bad Request, 401 Unauthorized, 404 Not Found)\n- **5xx** — server error (500 Internal Server Error, 503 Service Unavailable)\n\n## Stateless by design\n\nHTTP is **stateless** — each request is independent. The server doesn''t remember previous requests.\n\nThis is why cookies and sessions exist: to add state on top of a stateless protocol.\n\n> **Why stateless matters for scale**: Because the server remembers nothing, any server in a cluster can handle any request. This makes horizontal scaling simple — just add more servers.', 2, 'lesson', 10, true)
  returning id into l2;

  insert into public.lessons (id, path_id, slug, title, content_mdx, order_index, type, xp_reward, is_free)
  values (uuid_generate_v4(), foundations_id, 'apis-explained', 'APIs — The Interface Between Systems', E'## What is an API?\n\nAn API (Application Programming Interface) is a defined way for two pieces of software to communicate.\n\nThink of it as a contract: "If you send me a request in this format, I promise to send back a response in that format."\n\n## REST APIs\n\nREST (Representational State Transfer) is the dominant API style for web services. REST APIs:\n\n- Use HTTP methods (GET, POST, etc.) to express intent\n- Use URLs to identify resources\n- Return data as JSON (usually)\n- Are stateless\n\n```\nGET  /users/123        → get user 123\nPOST /users            → create a new user\nPUT  /users/123        → update user 123\nDELETE /users/123      → delete user 123\n```\n\n## What makes an API well-designed?\n\n**Consistency** — similar resources follow similar patterns.\n\n**Predictability** — the behaviour matches what the name implies.\n\n**Good errors** — 404 when something doesn''t exist. 400 with a message when the input is bad. Never 200 with an error in the body.\n\n**Versioning** — `/api/v1/users` so you can change things without breaking existing clients.\n\n## Beyond REST: GraphQL and gRPC\n\n**GraphQL** lets clients ask for exactly the data they need — no more, no less. Useful when clients have varying data needs (e.g. mobile vs desktop).\n\n**gRPC** uses binary encoding (Protocol Buffers) and HTTP/2. Much faster than REST JSON for internal service-to-service communication.\n\n> **Rule of thumb**: REST for public APIs. gRPC for internal services where performance matters. GraphQL when clients need flexible queries.', 3, 'lesson', 10, true)
  returning id into l3;

  insert into public.lessons (id, path_id, slug, title, content_mdx, order_index, type, xp_reward, is_free)
  values (uuid_generate_v4(), foundations_id, 'foundations-quiz', 'Foundations Quiz', E'Test your understanding of web fundamentals.', 4, 'quiz', 20, true)
  returning id into l4;

  insert into public.lessons (id, path_id, slug, title, content_mdx, order_index, type, xp_reward, is_free)
  values (uuid_generate_v4(), foundations_id, 'latency-and-throughput', 'Latency and Throughput', E'## The two dimensions of performance\n\nWhen someone says "the system is slow", they could mean two very different things:\n\n- **Latency** — how long does one request take? (measured in ms)\n- **Throughput** — how many requests can the system handle per second? (measured in req/s or RPS)\n\nA system can have low latency but low throughput. High throughput but high latency. The art is optimising both.\n\n## Latency numbers every engineer should know\n\n| Operation | Approximate latency |\n|-----------|--------------------|\n| L1 cache reference | 0.5 ns |\n| RAM access | 100 ns |\n| SSD read | 100 μs |\n| Network round trip (same datacenter) | 500 μs |\n| Network round trip (London → NYC) | 75 ms |\n| HDD seek | 10 ms |\n\n> These numbers reveal why caching matters so much: RAM is 200,000x faster than a disk read.\n\n## Percentiles, not averages\n\nNever trust average latency. Use **percentiles**:\n\n- **p50** — median, 50% of requests are faster\n- **p95** — 95% of requests are faster than this\n- **p99** — 99% of requests are faster than this\n\nThe p99 is where your users feel the pain. A p99 of 2s means 1 in 100 requests takes over 2 seconds — and that 1 in 100 request is often the most complex user.\n\n## The relationship between latency and throughput\n\nLittle''s Law: `throughput = concurrency / latency`\n\nIf your server handles 100 concurrent requests and average latency is 100ms, throughput is 1,000 req/s. To double throughput without changing latency, you need twice the concurrency — i.e. twice the servers.', 5, 'lesson', 10, true)
  returning id into l5;

  insert into public.lessons (id, path_id, slug, title, content_mdx, order_index, type, xp_reward, is_free)
  values (uuid_generate_v4(), foundations_id, 'cdn-and-caching-intro', 'CDNs and Caching Basics', E'## The speed of light is a real constraint\n\nA server in London can''t respond to a user in Sydney faster than physics allows. The round-trip alone is ~250ms at the speed of light through fibre.\n\nThe solution: **don''t serve content from London. Serve it from Sydney.**\n\n## Content Delivery Networks (CDNs)\n\nA CDN is a globally distributed network of servers (called **edge nodes** or **PoPs** — Points of Presence) that cache your content close to your users.\n\nHow it works:\n1. User in Sydney requests `yourapp.com/logo.png`\n2. DNS resolves to the nearest CDN edge node (Sydney)\n3. Edge node checks its cache — if it has the file, serves it directly (< 5ms)\n4. If not, it fetches from your **origin server** (London), caches it, then serves it\n5. All future Sydney users get it from the Sydney edge (fast!)\n\n## Cache-Control headers\n\nYou tell CDNs how long to cache content via HTTP headers:\n\n```\nCache-Control: public, max-age=86400\n```\n\nThis says: any cache (CDN, browser) can store this for 86,400 seconds (1 day).\n\n## What to cache vs not to cache\n\n**Cache aggressively**: images, fonts, CSS, JS bundles, videos\n\n**Cache carefully**: HTML pages (can use short TTLs or cache-busting)\n\n**Never cache**: user-specific data, auth tokens, anything private\n\n> **Key decision point**: When designing a system, ask "what can be served from cache?" before assuming everything needs a database hit.', 6, 'lesson', 10, true)
  returning id into l6;

  insert into public.lessons (id, path_id, slug, title, content_mdx, order_index, type, xp_reward, is_free)
  values (uuid_generate_v4(), foundations_id, 'load-balancing-intro', 'Load Balancing', E'## The problem: one server isn''t enough\n\nA single server has a ceiling: it can only handle so many concurrent requests before it slows down or crashes. Load balancing solves this.\n\n## What a load balancer does\n\nA load balancer sits in front of a pool of servers and distributes incoming requests across them.\n\n```\nUsers → Load Balancer → Server 1\n                     → Server 2\n                     → Server 3\n```\n\nIf Server 2 crashes, the load balancer stops sending it traffic. This gives you **high availability** — the system keeps working even when individual servers fail.\n\n## Load balancing strategies\n\n**Round robin** — requests go to servers in rotation (1, 2, 3, 1, 2, 3...). Simple, works well when requests are similar in cost.\n\n**Least connections** — sends each new request to the server with fewest active connections. Better when request processing time varies a lot.\n\n**IP hash** — the same client IP always goes to the same server. Useful when you need session stickiness.\n\n**Weighted** — some servers get more traffic than others. Useful when servers have different capacities.\n\n## Layer 4 vs Layer 7 load balancing\n\n**L4 (Transport layer)** — routes based on IP and port. Very fast, no knowledge of the request content.\n\n**L7 (Application layer)** — routes based on HTTP content (URL, headers, cookies). Slower but much more flexible. Can route `/api/*` to one server pool and `/static/*` to another.\n\n> Most modern systems use L7 load balancing (AWS ALB, nginx, HAProxy) because the flexibility is worth it.', 7, 'lesson', 10, true)
  returning id into l7;

  insert into public.lessons (id, path_id, slug, title, content_mdx, order_index, type, xp_reward, is_free)
  values (uuid_generate_v4(), foundations_id, 'foundations-final-quiz', 'Final Quiz — Foundations', E'Put it all together. 5 questions covering the full Foundations path.', 8, 'quiz', 25, true)
  returning id into l8;

  -- ── Quiz questions for Foundations Quiz (l4) ──────────────────────────

  insert into public.quiz_questions (lesson_id, text, options, correct_option_id, explanation, order_index)
  values
  (l4, 'What does HTTP status code 503 indicate?',
   '[{"id":"a","text":"The resource was not found"},{"id":"b","text":"The server is temporarily unavailable"},{"id":"c","text":"The request was malformed"},{"id":"d","text":"Authentication is required"}]',
   'b', '503 Service Unavailable means the server is temporarily unable to handle the request — usually due to overload or maintenance. 404 = not found, 400 = bad request, 401 = unauthorized.', 1),

  (l4, 'HTTP is described as "stateless". What does this mean?',
   '[{"id":"a","text":"HTTP doesn''t support encryption"},{"id":"b","text":"Each request is independent — the server doesn''t remember previous requests"},{"id":"c","text":"HTTP only works for static content"},{"id":"d","text":"The server never changes its response"}]',
   'b', 'Stateless means each HTTP request contains all the information needed to process it. The server has no memory of past requests from the same client. Sessions and cookies are built on top of HTTP to ADD state.', 2),

  (l4, 'A user types a URL and presses Enter. What happens FIRST?',
   '[{"id":"a","text":"A TCP connection is opened to the server"},{"id":"b","text":"The browser sends an HTTP GET request"},{"id":"c","text":"DNS resolves the domain to an IP address"},{"id":"d","text":"The TLS handshake begins"}]',
   'c', 'DNS resolution must happen first — the browser needs to know the IP address of the server before it can connect to it. DNS → TCP → TLS → HTTP is the correct order.', 3);

  -- ── Quiz questions for Final Quiz (l8) ────────────────────────────────

  insert into public.quiz_questions (lesson_id, text, options, correct_option_id, explanation, order_index)
  values
  (l8, 'You have one web server that''s running out of CPU under heavy load. Which approach directly addresses this?',
   '[{"id":"a","text":"Add a CDN"},{"id":"b","text":"Add a load balancer with more server instances"},{"id":"c","text":"Switch to a faster DNS provider"},{"id":"d","text":"Enable HTTP/2"}]',
   'b', 'A load balancer distributes traffic across multiple server instances, directly solving CPU overload on a single server. A CDN helps with static assets but doesn''t address application server load.', 1),

  (l8, 'Which metric tells you the WORST experience your users are having?',
   '[{"id":"a","text":"Average (mean) latency"},{"id":"b","text":"p50 latency"},{"id":"c","text":"p99 latency"},{"id":"d","text":"Throughput in req/s"}]',
   'c', 'p99 latency tells you what the slowest 1% of requests experience. Average latency hides outliers — a p99 of 3s is invisible in averages but very real to the users experiencing it.', 2),

  (l8, 'You''re designing a system serving images globally. Users in Australia complain about slow load times. The images are served from servers in London. What''s the best fix?',
   '[{"id":"a","text":"Increase the image server''s CPU"},{"id":"b","text":"Switch to faster image compression"},{"id":"c","text":"Put the images behind a CDN with edge nodes in Australia"},{"id":"d","text":"Use HTTP/3 instead of HTTP/2"}]',
   'c', 'The latency is physical — data traveling London → Australia takes ~250ms just for the round trip. A CDN with Australian edge nodes caches the images close to users, reducing latency to < 5ms.', 3),

  (l8, 'Which HTTP method should you use to partially update a user''s email address?',
   '[{"id":"a","text":"POST"},{"id":"b","text":"PUT"},{"id":"c","text":"PATCH"},{"id":"d","text":"UPDATE"}]',
   'c', 'PATCH is for partial updates — changing one or a few fields. PUT replaces the entire resource. POST creates a new resource. UPDATE is not an HTTP method.', 4),

  (l8, 'Your load balancer uses "round robin" routing. Server 1 handles a 500ms database query while Server 2 is idle. The next request comes in. Where does it go?',
   '[{"id":"a","text":"Server 1, because it''s already warm"},{"id":"b","text":"Server 2, because round robin goes in rotation"},{"id":"c","text":"Server 2, because least-connections picks it"},{"id":"d","text":"Whichever has lower CPU"}]',
   'b', 'Round robin goes in sequence regardless of server load. After Server 1, the next request goes to Server 2, then back to Server 1. "Least connections" would be smarter here — it would pick Server 2 because Server 1 has an active connection.', 5);

  -- ── Databases path — first 3 lessons ──────────────────────────────────

  insert into public.lessons (id, path_id, slug, title, content_mdx, order_index, type, xp_reward, is_free)
  values (uuid_generate_v4(), databases_id, 'sql-fundamentals', 'SQL Fundamentals', E'## Why every engineer needs to understand databases\n\nEvery application stores data. How you store it, retrieve it, and scale it determines whether your system handles 100 users or 100 million.\n\n## Relational databases and SQL\n\nRelational databases store data in **tables** (rows and columns) with defined relationships between them. SQL (Structured Query Language) is how you talk to them.\n\n### The core queries\n\n```sql\n-- Get all users\nSELECT * FROM users;\n\n-- Get specific fields with a condition\nSELECT id, email FROM users WHERE created_at > ''2024-01-01'';\n\n-- Join two tables\nSELECT users.email, orders.total\nFROM orders\nJOIN users ON orders.user_id = users.id\nWHERE orders.status = ''paid'';\n\n-- Aggregate: count orders per user\nSELECT user_id, COUNT(*) as order_count\nFROM orders\nGROUP BY user_id\nHAVING COUNT(*) > 5;\n```\n\n## ACID properties\n\nRelational databases guarantee **ACID**:\n\n- **Atomicity** — a transaction either fully completes or fully fails. No partial writes.\n- **Consistency** — data always satisfies defined rules (constraints, foreign keys).\n- **Isolation** — concurrent transactions don''t interfere with each other.\n- **Durability** — committed data survives crashes.\n\n> This is why you use Postgres for financial transactions, user accounts, and anything where data integrity matters more than raw speed.\n\n## When NOT to use SQL\n\nRelational databases struggle when:\n- You need to store documents with varying structure (use MongoDB)\n- You need key-value lookups at massive scale (use Redis or DynamoDB)\n- You need to store time-series data (use InfluxDB or TimescaleDB)\n- You need graph traversals (use Neo4j)', 1, 'lesson', 10, true)
  returning id into d1;

  insert into public.lessons (id, path_id, slug, title, content_mdx, order_index, type, xp_reward, is_free)
  values (uuid_generate_v4(), databases_id, 'indexes-explained', 'Database Indexes', E'## The most impactful 5 minutes of performance work\n\nAdding the right index to a database table can take a query from 30 seconds to 3 milliseconds. No code change. No new servers. Just an index.\n\n## What is an index?\n\nAn index is a separate data structure (usually a B-tree) that the database maintains alongside your table. It lets the database find rows without scanning every row in the table.\n\nWithout an index:\n```sql\nSELECT * FROM orders WHERE user_id = 12345;\n-- Database scans ALL rows: O(n)\n```\n\nWith an index on `user_id`:\n```sql\nCREATE INDEX idx_orders_user_id ON orders(user_id);\n-- Database jumps directly to matching rows: O(log n)\n```\n\n## The tradeoff\n\nIndexes aren''t free:\n- **Slower writes** — every INSERT, UPDATE, DELETE must also update the index\n- **More storage** — the index data structure takes disk space\n\nRule of thumb: **index columns you filter or sort by frequently**. Don''t index everything.\n\n## Composite indexes\n\nAn index can cover multiple columns:\n\n```sql\nCREATE INDEX idx_orders_user_status \nON orders(user_id, status);\n```\n\nThis is efficient for:\n```sql\nSELECT * FROM orders WHERE user_id = 123 AND status = ''paid'';\n```\n\nBut NOT efficient for just `WHERE status = ''paid''` — the leftmost column rule.\n\n## When queries are still slow despite indexes\n\nUse `EXPLAIN ANALYZE` to see what the database is actually doing:\n\n```sql\nEXPLAIN ANALYZE SELECT * FROM orders WHERE user_id = 123;\n```\n\nLook for "Seq Scan" (bad — full table scan) vs "Index Scan" (good).', 2, 'lesson', 10, true)
  returning id into d2;

  insert into public.lessons (id, path_id, slug, title, content_mdx, order_index, type, xp_reward, is_free)
  values (uuid_generate_v4(), databases_id, 'replication-and-scaling', 'Replication and Scaling', E'## When one database isn''t enough\n\nYour application starts with one database. It works. Then traffic grows, and suddenly that database is the bottleneck. What do you do?\n\n## Read replicas\n\nMost applications read far more than they write (10:1 or higher). **Read replicas** exploit this asymmetry.\n\nHow it works:\n- One **primary** database handles all writes\n- One or more **replicas** receive a copy of every write (via replication log)\n- Read queries are distributed across replicas\n- Write queries always go to the primary\n\n```\nApp → Primary (writes)\n    → Replica 1 (reads)\n    → Replica 2 (reads)\n    → Replica 3 (reads)\n```\n\n**The tradeoff**: replicas are **eventually consistent**. There''s a small lag (usually < 1s) between a write hitting the primary and appearing on replicas. Don''t read from a replica right after a write if you need to see that write.\n\n## Sharding (horizontal partitioning)\n\nWhen a single primary can''t handle write volume, you **shard** — split data across multiple database instances.\n\nExample: shard users by `user_id % 4`:\n- Shard 0: users 0, 4, 8, 12...\n- Shard 1: users 1, 5, 9, 13...\n- Shard 2: users 2, 6, 10, 14...\n- Shard 3: users 3, 7, 11, 15...\n\n**The tradeoff**: sharding makes cross-shard queries very hard. `JOIN` across shards = pain. Choose your shard key carefully.\n\n> **Rule of thumb**: add read replicas first (easy, huge win). Only shard when you''ve exhausted vertical scaling and read replicas.', 3, 'lesson', 10, true)
  returning id into d3;

end $$;
